### ISSUE TITLE
Download as PDF

### ISSUE THREAD

**Issue by attah** [Logic-gate/harbour-cargo#1]
Thank you very much for a truly useful app!
Is there any chance you could add "Download as PDF"? (Or maybe "Download as ...", and a menu to choose from available formats)
Google drive has quite good PDF conversion that would be very nice to be able to take advantage of.

My primary use case is for printing, but i imagine sharing over email etc or just getting something that renders reliably can be useful.
(BTW, maybe a sharing menu would be nice?)
I find that the sailfish office app mangles quite a lot of documents, and this could help work around that.

I tried hacking it in with setting mimeType to "application/pdf" on the download function, but it doesn't seem to work. :/

**Comment by attah** [comment]
I figured out what i was doing wrong. Apparently keyword arguments doesn't work in pyotherside.
I have opened a pull request, but feel free to make something nicer than my quick hack.

There is one problem though... the PDF documents i get seem to be in letter format, and not the native A4 that they are in on my Google Drive.
Do you have any idea what could be causing this? Does the app need to share its locale settings with the server somehow?

**Comment by attah** [comment]
Hmm, seems it must have been a server-side hiccup that gave the wrong paper size. Today it works fine.

**Comment by Logic-gate** [comment]
Hey,

For some reason github was not forwarding notification to me. Apologies for the late response.

**Comment by attah** [comment]
No worries, should i perhaps have poked you by email?

**Comment by Logic-gate** [comment]
Mind checking this out https://github.com/Logic-gate/harbour-cargo/commit/d8c5baa9a135d2660175c13d07efd8c78d9c4c46 if all is good I can merge your PR.  

Release: https://github.com/Logic-gate/harbour-cargo/releases/tag/1.0.3

**Comment by attah** [comment]
Hmmm. I am unable to get the sharing menu to show for native Google Drive documents after downloading. It only seems to work for things like docx and jpeg.

I'm also not so sure the average user cares too much about what is technically save or export for weird google formats. 
They would probably be fine with any known format for the Download action.
The Download action is also still only called Download on the first page.

Open is a very good addition (did not test this), but I think it is a bit brave to push pages from Sailfish Office... 
https://doc.qt.io/qt-5/qml-qtqml-qt.html#openUrlExternally-method should be safer.
Agreed, a new page is a bit nicer user experience than opening another app, but it feels a bit fragile.
